version: 2
updates:

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "20:30"
      timezone: "Europe/Paris"
    target-branch: development

  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "20:30"
      timezone: "Europe/Paris"
    target-branch: development

  - package-ecosystem: npm
    directory: "/backend/servers/explorer-web"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "20:30"
      timezone: "Europe/Paris"
    target-branch: development